### ISSUE TITLE
CRUD functionality for games

### ISSUE THREAD

**Issue by jessietech08** [jessietech08/eCommerceSite#5]
- [ ] Set up model for Games
- [ ] Create database and table for Games
- [ ] Add Crete page for Games
- [ ] Add Select page (Game catalog page)
- [ ] Add Update page for Games
- [ ] Add Delete page for Games
